export const MapBestStatusDescriptions: Record<any, string> = {
  211: "Đang đi lấy hàng",
  203: "Lấy hàng không thành công",
  202: "Lấy hàng thành công",
  301: "Nhận hàng vào bưu cục Nguồn",
  302: "Xuất hàng đến trung tâm khai thác (trung tâm chia chọn)",
  303: "Nhận hàng vào trung tâm khai thác (trung tâm chia chọn)",
  304: "Xuất hàng khỏi trung tâm khai thác (trung tâm chia chọn)",
  309: "Nhận hàng vào bưu cục phát hàng",
  601: "Xuất hàng để đi giao",
  604: "Giao hàng không thành công",
  666: "Giao hàng thành công",
  605: "Xác nhận chuyển hoàn",
  701: "Xuất hàng khỏi bưu cục phát để trả về",
  702: "Nhận hàng vào trung tâm khai thác (trung tâm chia chọn) để trả về",
  703: "Xuất hàng khỏi trung tâm khai thác (trung tâm chia chọn) để trả về",
  704: "Nhận hàng vào bưu cục trả hàng",
  705: "Xuất hàng để trả về",
  707: "Trả hàng không thành công",
  708: "Trả hàng thành công",
  777: "Thất lạc",
  1000: "Hư hỏng (Damage)",
  "customer Cancel": "Hủy đơn",
};

export const MapBestStatusToNewStatus: Record<any, string> = {
  211: "PROCESSING",
  203: "PENDING", //lay hang that bai
  202: "SHIPPED", //dang lay hang, -> doi trang thai thanh dang giao
  301: "SHIPPED", //Nhận hàng vào bưu cục Nguồn
  302: "SHIPPED",
  303: "SHIPPED",
  304: "SHIPPED",
  309: "SHIPPED",
  601: "SHIPPED",
  604: "SHIPPED",
  666: "COMPLETED",
  605: "RETURNED",
  701: "RETURNED",
  702: "RETURNED",
  703: "RETURNED",
  704: "RETURNED",
  705: "RETURNED",
  707: "RETURNED",
  708: "RETURNED",
  777: "RETURNED",
  1000: "RETURNED",
  ["customer Cancel"]: "CANCELLED",
};

export const MapBestStatusContent: Record<string, string> = {
  "customer cancel the order": "Khách hàng hủy đơn",
};

export const MapShippingUnit: Record<string, string> = {
  BEST: "BEST",
  OTHER: "Khác",
  GHN: "GHN",
};

export const MapGhnStatusToNewStatus: Record<any, string> = {
  ready_to_pick: "PENDING",
  picking: "PROCESSING",
  cancel: "CANCELLED",
  money_collect_picking: "PROCESSING",
  picked: "SHIPPED",
  storing: "SHIPPED",
  transporting: "SHIPPED",
  sorting: "SHIPPED",
  delivering: "SHIPPED",
  money_collect_delivering: "SHIPPED",
  delivered: "COMPLETED",
  delivery_fail: "SHIPPED",
  waiting_to_return: "SHIPPED",
  return: "RETURNED",
  return_transporting: "RETURNED",
  return_sorting: "RETURNED",
  returning: "RETURNED",
  return_fail: "RETURNED",
  returned: "RETURNED",
  exception: "RETURNED",
  damage: "RETURNED",
  lost: "RETURNED",
};

export const MapGhnStatusDescriptions: Record<any, string> = {
  ready_to_pick: "Người bán đang chuẩn bị hàng",
  picking: "Đơn vị vận chuyển đang lấy hàng",
  cancel: "Huỷ đơn",
  money_collect_picking: "Đơn vị vận chuyển đang lấy hàng",
  picked: "Đơn vị vận chuyển lấy hàng thành công",
  storing: "Hàng đã chuyển về trung tâm phân loại",
  transporting: "Hàng hóa đang được luân chuyển",
  sorting: "Hàng hóa đang được phân loại",
  delivering: "Đơn hàng đang trên đường giao đến bạn",
  money_collect_delivering: "Đơn hàng đang trên đường giao đến bạn",
  delivered: "Giao hàng thành công",
  delivery_fail: "Giao hàng không thành công",
  waiting_to_return: "Đang giao lại hàng",
  return: "Hàng đang chờ trả lại",
  return_transporting: "Hàng hóa đang được luân chuyển",
  return_sorting: "Hàng hóa đang được phân loại",
  returning: "Hàng đang được trả về",
  return_fail: "Trả hàng thất bại",
  returned: "Trả hàng thành công",
  exception: "Hàng đang được trả về",
  damage: "Hư hỏng",
  lost: "Thất lạc",
};
